//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitraisExercise.Test.BODSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DistributorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid BodsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodsFullNameField;
        
        private MitraisExercise.Test.BODSService.Status BodsStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid BodsId {
            get {
                return this.BodsIdField;
            }
            set {
                if ((this.BodsIdField.Equals(value) != true)) {
                    this.BodsIdField = value;
                    this.RaisePropertyChanged("BodsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BodsFullName {
            get {
                return this.BodsFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BodsFullNameField, value) != true)) {
                    this.BodsFullNameField = value;
                    this.RaisePropertyChanged("BodsFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public MitraisExercise.Test.BODSService.Status BodsStatus {
            get {
                return this.BodsStatusField;
            }
            set {
                if ((this.BodsStatusField.Equals(value) != true)) {
                    this.BodsStatusField = value;
                    this.RaisePropertyChanged("BodsStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://tempuri.org/")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InActive = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Archived = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapServiceResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SoapServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ProcessResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MitraisExercise.Test.BODSService.ArrayOfString ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MitraisExercise.Test.BODSService.DistributorModel[] DataResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ProcessResult {
            get {
                return this.ProcessResultField;
            }
            set {
                if ((this.ProcessResultField.Equals(value) != true)) {
                    this.ProcessResultField = value;
                    this.RaisePropertyChanged("ProcessResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MitraisExercise.Test.BODSService.ArrayOfString ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MitraisExercise.Test.BODSService.DistributorModel[] DataResults {
            get {
                return this.DataResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataResultsField, value) != true)) {
                    this.DataResultsField = value;
                    this.RaisePropertyChanged("DataResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FilterModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid DistributorIdField;
        
        private MitraisExercise.Test.BODSService.Status DistributorStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid DistributorId {
            get {
                return this.DistributorIdField;
            }
            set {
                if ((this.DistributorIdField.Equals(value) != true)) {
                    this.DistributorIdField = value;
                    this.RaisePropertyChanged("DistributorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MitraisExercise.Test.BODSService.Status DistributorStatus {
            get {
                return this.DistributorStatusField;
            }
            set {
                if ((this.DistributorStatusField.Equals(value) != true)) {
                    this.DistributorStatusField = value;
                    this.RaisePropertyChanged("DistributorStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BODSService.BODSServiceSoap")]
    public interface BODSServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDistributorRecord", ReplyAction="*")]
        MitraisExercise.Test.BODSService.AddDistributorRecordResponse AddDistributorRecord(MitraisExercise.Test.BODSService.AddDistributorRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDistributorRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.AddDistributorRecordResponse> AddDistributorRecordAsync(MitraisExercise.Test.BODSService.AddDistributorRecordRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributorRecord", ReplyAction="*")]
        MitraisExercise.Test.BODSService.UpdateDistributorRecordResponse UpdateDistributorRecord(MitraisExercise.Test.BODSService.UpdateDistributorRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributorRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.UpdateDistributorRecordResponse> UpdateDistributorRecordAsync(MitraisExercise.Test.BODSService.UpdateDistributorRecordRequest request);
        
        // CODEGEN: Generating message contract since element name filter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterDistributorRecord", ReplyAction="*")]
        MitraisExercise.Test.BODSService.FilterDistributorRecordResponse FilterDistributorRecord(MitraisExercise.Test.BODSService.FilterDistributorRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterDistributorRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.FilterDistributorRecordResponse> FilterDistributorRecordAsync(MitraisExercise.Test.BODSService.FilterDistributorRecordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDistributorRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDistributorRecord", Namespace="http://tempuri.org/", Order=0)]
        public MitraisExercise.Test.BODSService.AddDistributorRecordRequestBody Body;
        
        public AddDistributorRecordRequest() {
        }
        
        public AddDistributorRecordRequest(MitraisExercise.Test.BODSService.AddDistributorRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDistributorRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MitraisExercise.Test.BODSService.DistributorModel entity;
        
        public AddDistributorRecordRequestBody() {
        }
        
        public AddDistributorRecordRequestBody(MitraisExercise.Test.BODSService.DistributorModel entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDistributorRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDistributorRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public MitraisExercise.Test.BODSService.AddDistributorRecordResponseBody Body;
        
        public AddDistributorRecordResponse() {
        }
        
        public AddDistributorRecordResponse(MitraisExercise.Test.BODSService.AddDistributorRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDistributorRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MitraisExercise.Test.BODSService.SoapServiceResponse AddDistributorRecordResult;
        
        public AddDistributorRecordResponseBody() {
        }
        
        public AddDistributorRecordResponseBody(MitraisExercise.Test.BODSService.SoapServiceResponse AddDistributorRecordResult) {
            this.AddDistributorRecordResult = AddDistributorRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDistributorRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDistributorRecord", Namespace="http://tempuri.org/", Order=0)]
        public MitraisExercise.Test.BODSService.UpdateDistributorRecordRequestBody Body;
        
        public UpdateDistributorRecordRequest() {
        }
        
        public UpdateDistributorRecordRequest(MitraisExercise.Test.BODSService.UpdateDistributorRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDistributorRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MitraisExercise.Test.BODSService.DistributorModel entity;
        
        public UpdateDistributorRecordRequestBody() {
        }
        
        public UpdateDistributorRecordRequestBody(MitraisExercise.Test.BODSService.DistributorModel entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDistributorRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDistributorRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public MitraisExercise.Test.BODSService.UpdateDistributorRecordResponseBody Body;
        
        public UpdateDistributorRecordResponse() {
        }
        
        public UpdateDistributorRecordResponse(MitraisExercise.Test.BODSService.UpdateDistributorRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDistributorRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MitraisExercise.Test.BODSService.SoapServiceResponse UpdateDistributorRecordResult;
        
        public UpdateDistributorRecordResponseBody() {
        }
        
        public UpdateDistributorRecordResponseBody(MitraisExercise.Test.BODSService.SoapServiceResponse UpdateDistributorRecordResult) {
            this.UpdateDistributorRecordResult = UpdateDistributorRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilterDistributorRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilterDistributorRecord", Namespace="http://tempuri.org/", Order=0)]
        public MitraisExercise.Test.BODSService.FilterDistributorRecordRequestBody Body;
        
        public FilterDistributorRecordRequest() {
        }
        
        public FilterDistributorRecordRequest(MitraisExercise.Test.BODSService.FilterDistributorRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilterDistributorRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MitraisExercise.Test.BODSService.FilterModel filter;
        
        public FilterDistributorRecordRequestBody() {
        }
        
        public FilterDistributorRecordRequestBody(MitraisExercise.Test.BODSService.FilterModel filter) {
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilterDistributorRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilterDistributorRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public MitraisExercise.Test.BODSService.FilterDistributorRecordResponseBody Body;
        
        public FilterDistributorRecordResponse() {
        }
        
        public FilterDistributorRecordResponse(MitraisExercise.Test.BODSService.FilterDistributorRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilterDistributorRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MitraisExercise.Test.BODSService.SoapServiceResponse FilterDistributorRecordResult;
        
        public FilterDistributorRecordResponseBody() {
        }
        
        public FilterDistributorRecordResponseBody(MitraisExercise.Test.BODSService.SoapServiceResponse FilterDistributorRecordResult) {
            this.FilterDistributorRecordResult = FilterDistributorRecordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BODSServiceSoapChannel : MitraisExercise.Test.BODSService.BODSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BODSServiceSoapClient : System.ServiceModel.ClientBase<MitraisExercise.Test.BODSService.BODSServiceSoap>, MitraisExercise.Test.BODSService.BODSServiceSoap {
        
        public BODSServiceSoapClient() {
        }
        
        public BODSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BODSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BODSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BODSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MitraisExercise.Test.BODSService.AddDistributorRecordResponse MitraisExercise.Test.BODSService.BODSServiceSoap.AddDistributorRecord(MitraisExercise.Test.BODSService.AddDistributorRecordRequest request) {
            return base.Channel.AddDistributorRecord(request);
        }
        
        public MitraisExercise.Test.BODSService.SoapServiceResponse AddDistributorRecord(MitraisExercise.Test.BODSService.DistributorModel entity) {
            MitraisExercise.Test.BODSService.AddDistributorRecordRequest inValue = new MitraisExercise.Test.BODSService.AddDistributorRecordRequest();
            inValue.Body = new MitraisExercise.Test.BODSService.AddDistributorRecordRequestBody();
            inValue.Body.entity = entity;
            MitraisExercise.Test.BODSService.AddDistributorRecordResponse retVal = ((MitraisExercise.Test.BODSService.BODSServiceSoap)(this)).AddDistributorRecord(inValue);
            return retVal.Body.AddDistributorRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.AddDistributorRecordResponse> MitraisExercise.Test.BODSService.BODSServiceSoap.AddDistributorRecordAsync(MitraisExercise.Test.BODSService.AddDistributorRecordRequest request) {
            return base.Channel.AddDistributorRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.AddDistributorRecordResponse> AddDistributorRecordAsync(MitraisExercise.Test.BODSService.DistributorModel entity) {
            MitraisExercise.Test.BODSService.AddDistributorRecordRequest inValue = new MitraisExercise.Test.BODSService.AddDistributorRecordRequest();
            inValue.Body = new MitraisExercise.Test.BODSService.AddDistributorRecordRequestBody();
            inValue.Body.entity = entity;
            return ((MitraisExercise.Test.BODSService.BODSServiceSoap)(this)).AddDistributorRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MitraisExercise.Test.BODSService.UpdateDistributorRecordResponse MitraisExercise.Test.BODSService.BODSServiceSoap.UpdateDistributorRecord(MitraisExercise.Test.BODSService.UpdateDistributorRecordRequest request) {
            return base.Channel.UpdateDistributorRecord(request);
        }
        
        public MitraisExercise.Test.BODSService.SoapServiceResponse UpdateDistributorRecord(MitraisExercise.Test.BODSService.DistributorModel entity) {
            MitraisExercise.Test.BODSService.UpdateDistributorRecordRequest inValue = new MitraisExercise.Test.BODSService.UpdateDistributorRecordRequest();
            inValue.Body = new MitraisExercise.Test.BODSService.UpdateDistributorRecordRequestBody();
            inValue.Body.entity = entity;
            MitraisExercise.Test.BODSService.UpdateDistributorRecordResponse retVal = ((MitraisExercise.Test.BODSService.BODSServiceSoap)(this)).UpdateDistributorRecord(inValue);
            return retVal.Body.UpdateDistributorRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.UpdateDistributorRecordResponse> MitraisExercise.Test.BODSService.BODSServiceSoap.UpdateDistributorRecordAsync(MitraisExercise.Test.BODSService.UpdateDistributorRecordRequest request) {
            return base.Channel.UpdateDistributorRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.UpdateDistributorRecordResponse> UpdateDistributorRecordAsync(MitraisExercise.Test.BODSService.DistributorModel entity) {
            MitraisExercise.Test.BODSService.UpdateDistributorRecordRequest inValue = new MitraisExercise.Test.BODSService.UpdateDistributorRecordRequest();
            inValue.Body = new MitraisExercise.Test.BODSService.UpdateDistributorRecordRequestBody();
            inValue.Body.entity = entity;
            return ((MitraisExercise.Test.BODSService.BODSServiceSoap)(this)).UpdateDistributorRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MitraisExercise.Test.BODSService.FilterDistributorRecordResponse MitraisExercise.Test.BODSService.BODSServiceSoap.FilterDistributorRecord(MitraisExercise.Test.BODSService.FilterDistributorRecordRequest request) {
            return base.Channel.FilterDistributorRecord(request);
        }
        
        public MitraisExercise.Test.BODSService.SoapServiceResponse FilterDistributorRecord(MitraisExercise.Test.BODSService.FilterModel filter) {
            MitraisExercise.Test.BODSService.FilterDistributorRecordRequest inValue = new MitraisExercise.Test.BODSService.FilterDistributorRecordRequest();
            inValue.Body = new MitraisExercise.Test.BODSService.FilterDistributorRecordRequestBody();
            inValue.Body.filter = filter;
            MitraisExercise.Test.BODSService.FilterDistributorRecordResponse retVal = ((MitraisExercise.Test.BODSService.BODSServiceSoap)(this)).FilterDistributorRecord(inValue);
            return retVal.Body.FilterDistributorRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.FilterDistributorRecordResponse> MitraisExercise.Test.BODSService.BODSServiceSoap.FilterDistributorRecordAsync(MitraisExercise.Test.BODSService.FilterDistributorRecordRequest request) {
            return base.Channel.FilterDistributorRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MitraisExercise.Test.BODSService.FilterDistributorRecordResponse> FilterDistributorRecordAsync(MitraisExercise.Test.BODSService.FilterModel filter) {
            MitraisExercise.Test.BODSService.FilterDistributorRecordRequest inValue = new MitraisExercise.Test.BODSService.FilterDistributorRecordRequest();
            inValue.Body = new MitraisExercise.Test.BODSService.FilterDistributorRecordRequestBody();
            inValue.Body.filter = filter;
            return ((MitraisExercise.Test.BODSService.BODSServiceSoap)(this)).FilterDistributorRecordAsync(inValue);
        }
    }
}
